# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            No Painkiller In Cloud
tagline:          'Break it then fix it, but one at a time'
description:      'Thoughts on Virtualization, Storage, Networking, Open Source and Open Standard'
url:              http://hannibalhuang.github.io
baseurl:          /

author:
  name:           'Howard Huang'
  url:            https://twitter.com/nopainkiller

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/hannibalhuang/
